# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(338, 206)
        self.gridLayout = QtWidgets.QGridLayout(Calculator)
        self.gridLayout.setObjectName("gridLayout")
        self.display = QtWidgets.QLineEdit(Calculator)
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 0, 1, 1, 2)
        self.push1 = QtWidgets.QPushButton(Calculator)
        self.push1.setObjectName("push1")
        self.gridLayout.addWidget(self.push1, 1, 0, 1, 1)
        self.push2 = QtWidgets.QPushButton(Calculator)
        self.push2.setObjectName("push2")
        self.gridLayout.addWidget(self.push2, 1, 1, 1, 1)
        self.push4 = QtWidgets.QPushButton(Calculator)
        self.push4.setObjectName("push4")
        self.gridLayout.addWidget(self.push4, 2, 0, 1, 1)
        self.push5 = QtWidgets.QPushButton(Calculator)
        self.push5.setObjectName("push5")
        self.gridLayout.addWidget(self.push5, 2, 1, 1, 1)
        self.push7 = QtWidgets.QPushButton(Calculator)
        self.push7.setObjectName("push7")
        self.gridLayout.addWidget(self.push7, 3, 0, 1, 1)
        self.push8 = QtWidgets.QPushButton(Calculator)
        self.push8.setObjectName("push8")
        self.gridLayout.addWidget(self.push8, 3, 1, 1, 1)
        self.push0 = QtWidgets.QPushButton(Calculator)
        self.push0.setObjectName("push0")
        self.gridLayout.addWidget(self.push0, 4, 0, 1, 1)
        self.push_equal = QtWidgets.QPushButton(Calculator)
        self.push_equal.setObjectName("push_equal")
        self.gridLayout.addWidget(self.push_equal, 4, 1, 1, 1)
        self.push3 = QtWidgets.QPushButton(Calculator)
        self.push3.setObjectName("push3")
        self.gridLayout.addWidget(self.push3, 1, 2, 1, 1)
        self.push6 = QtWidgets.QPushButton(Calculator)
        self.push6.setObjectName("push6")
        self.gridLayout.addWidget(self.push6, 2, 2, 1, 1)
        self.push9 = QtWidgets.QPushButton(Calculator)
        self.push9.setObjectName("push9")
        self.gridLayout.addWidget(self.push9, 3, 2, 1, 1)
        self.push_clear = QtWidgets.QPushButton(Calculator)
        self.push_clear.setObjectName("push_clear")
        self.gridLayout.addWidget(self.push_clear, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_point = QtWidgets.QPushButton(Calculator)
        self.push_point.setObjectName("push_point")
        self.horizontalLayout.addWidget(self.push_point)
        self.push_add = QtWidgets.QPushButton(Calculator)
        self.push_add.setObjectName("push_add")
        self.horizontalLayout.addWidget(self.push_add)
        self.push_minus = QtWidgets.QPushButton(Calculator)
        self.push_minus.setObjectName("push_minus")
        self.horizontalLayout.addWidget(self.push_minus)
        self.push_multiply = QtWidgets.QPushButton(Calculator)
        self.push_multiply.setObjectName("push_multiply")
        self.horizontalLayout.addWidget(self.push_multiply)
        self.push_divide = QtWidgets.QPushButton(Calculator)
        self.push_divide.setObjectName("push_divide")
        self.horizontalLayout.addWidget(self.push_divide)
        self.push_delete = QtWidgets.QPushButton(Calculator)
        self.push_delete.setObjectName("push_delete")
        self.horizontalLayout.addWidget(self.push_delete)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 3)

        self.push_minus.clicked.connect(self.action_minus)
        self. push_equal.clicked.connect(self.action_equal)
        self.push0.clicked.connect(self.action0)
        self.push1.clicked.connect(self.action1)
        self.push2.clicked.connect(self.action2)
        self.push3.clicked.connect(self.action3)
        self.push4.clicked.connect(self.action4)
        self.push5.clicked.connect(self.action5)
        self. push6.clicked.connect(self.action6)
        self.push7.clicked.connect(self.action7)
        self. push8.clicked.connect(self.action8)
        self. push9.clicked.connect(self.action9)
        self.push_divide.clicked.connect(self.action_div)
        self.push_multiply.clicked.connect(self.action_mul)
        self.push_add.clicked.connect(self.action_plus)
        self.push_point.clicked.connect(self.action_point)
        self.push_clear.clicked.connect(self.action_clear)
        self.push_delete.clicked.connect(self.action_del)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Form"))
        self.push1.setText(_translate("Calculator", "1"))
        self.push2.setText(_translate("Calculator", "2"))
        self.push4.setText(_translate("Calculator", "4"))
        self.push5.setText(_translate("Calculator", "5"))
        self.push7.setText(_translate("Calculator", "7"))
        self.push8.setText(_translate("Calculator", "8"))
        self.push0.setText(_translate("Calculator", "0"))
        self.push_equal.setText(_translate("Calculator", "="))
        self.push3.setText(_translate("Calculator", "3"))
        self.push6.setText(_translate("Calculator", "6"))
        self.push9.setText(_translate("Calculator", "9"))
        self.push_clear.setText(_translate("Calculator", "C"))
        self.push_point.setText(_translate("Calculator", "."))
        self.push_add.setText(_translate("Calculator", "+"))
        self.push_minus.setText(_translate("Calculator", "-"))
        self.push_multiply.setText(_translate("Calculator", "*"))
        self.push_divide.setText(_translate("Calculator", "/"))
        self.push_delete.setText(_translate("Calculator", "Delete"))

    def action_equal(self):

        # get the label text
        equation = self.display.text()

        try:
            # getting the ans
            ans = eval(equation)

            # setting text to the label
            self.display.setText(str(ans))

        except:
            # setting text to the label
            self.display.setText("Wrong Input")


    def action_plus(self):
       # appending label text
        text = self.display.text()
        self.display.setText(text + " + ")


    def action_minus(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + " - ")


    def action_div(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + " / ")


    def action_mul(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + " * ")


    def action_point(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + ".")


    def action0(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "0")


    def action1(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "1")


    def action2(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "2")


    def action3(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "3")


    def action4(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "4")


    def action5(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "5")


    def action6(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "6")


    def action7(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "7")


    def action8(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "8")


    def action9(self):
        # appending label text
        text = self.display.text()
        self.display.setText(text + "9")


    def action_clear(self):
        # clearing the label text
        self.display.setText("")


    def action_del(self):
        # clearing a single digit
        text = self.display.text()
        print(text[:len(text) - 1])
        self.display.setText(text[:len(text) - 1])


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QWidget()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())


